# Generated by Django 2.1.3 on 2018-11-13 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
